### ISSUE TITLE
error (cant lvlup player)

### ISSUE THREAD

**Issue by wundertraume** [AdvancedPlugins/Jobs#20] opened 2024-04-09 17:29 UTC
### Describe the bug

If you try to raise a player's job level, nothing happens, unless you put a number at the end - gives an error

### How to reproduce

`/advancedjobs:ajadmin levelup player Атлет`

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Jobs/assets/118831819/53142aaf-bab9-4ca1-b836-3a066c832536)
![image](https://github.com/AdvancedPlugins/Jobs/assets/118831819/99243d66-b579-47cd-baf4-35152c67a1b5)

**Comment by KPGTB** [comment] 2024-04-09 18:23
Hey! The syntax of this command is:
`/advancedjobs:ajadmin levelup PLAYER_NAME JOB_NAME`
NOTE: JOB_NAME is a name of file with configuration of this job (without .yml) [it's job id].

Error from console is caused by another bug - it should display that job doesn't exist - it will be fixed in the next update

**Closed** 2024-04-14 18:26 UTC
Labels: bug, Resolved
